name: Mika Vanhanen
favicon: null
layout_spectrum: 0.43244
typography_spectrum: 0.46971
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#070709'
    - '#6f6559'
    - '#2f3930'
    - '#99bae5'
  brandStrength: 0.20314098009839654
  lightness: 0.145229002693668
  saturation: 0.6232531862333417
  rhythmicContrast: 0.6007438045926392
purpose: []
